### ISSUE TITLE
pack type convert error

### ISSUE THREAD

**Issue by saibing** [agenium-scale/boost.simd#21] opened 2015-10-27 09:18 UTC
# code

``` cpp

#include <boost/simd/sdk/simd/pack.hpp> 
#include <boost/simd/sdk/simd/io.hpp>
#include <boost/simd/include/functions/load.hpp>
#include <boost/simd/include/functions/evaluate.hpp>
#include <boost/simd/operator/include/functions/plus.hpp>
#include <iostream>

using namespace std;
using namespace boost::simd;

#define SECONDS_IN_ONE_DAY      86400

template <typename T>
class op_boost_utc_add
{
    typedef boost::simd::pack<T, 16 / sizeof(T)> p_t;
    const p_t seconds_in_one_day = boost::simd::splat<p_t>(SECONDS_IN_ONE_DAY);

public:
    p_t operator()(p_t const &a0, p_t const &a1, p_t const &delta)
    {
        return evaluate(a0 + (seconds_in_one_day * a1) + delta);
    }
};

int main()
{
    typedef boost::simd::pack<long long, 2> p_l_t;

    p_l_t a(10, 100);
    p_l_t b(10, 100);
    p_l_t c(1, 1);

    p_l_t r = op_boost_utc_add<long long>()(a, b, c);

    cout << r << endl;                                                               

    return 0;
}   

```
# boost.simd version

3.1.0
# boost version

1_59_0
# compiler version
- clang++ 3.6
- gcc 4.8.2
# issue

**gcc compile error, but clang++ is ok.**

``` bash

[d257414 boost]$g++ -g -o add add.cpp -I${BOOST_ROOT_DIR} -I${BOOST_SIMD_DIR}/include -msse4.1 -std=c++11
add.cpp: In constructor ‘constexpr op_boost_utc_add<long long int>::op_boost_utc_add()’:
add.cpp:45:7: error: conversion from ‘boost::dispatch::meta::result_of<boost::simd::ext::implement<boost::simd::tag::splat_(boost::dispatch::meta::scalar_<boost::dispatch::meta::fundamental_<int> >, boost::dispatch::meta::target_<boost::dispatch::meta::ast_<boost::dispatch::meta::as_<boost::simd::pack<long long int, 2ul> >, boost::simd::domain> >), boost::dispatch::tag::cpu_, void>(int, boost::dispatch::meta::as_<boost::simd::pack<long long int, 2ul> >), void>::type {aka boost::simd::expression<boost::proto::exprns_::expr<boost::simd::tag::splat_, boost::proto::argsns_::list2<boost::simd::expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<int>, 0l>, int>, boost::simd::expression<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::dispatch::meta::as_<boost::simd::native<long long int, boost::simd::tag::sse_, void> > >, 0l>, boost::dispatch::meta::as_<boost::simd::native<long long int, boost::simd::tag::sse_, void> > > >, 2l>, boost::simd::native<long long int, boost::simd::tag::sse_, void> >}’ to non-scalar type ‘const p_t {aka const boost::simd::pack<long long int, 2ul>}’ requested
 class op_boost_utc_add
       ^
add.cpp: In function ‘int main()’:
add.cpp:66:43: note: synthesized method ‘constexpr op_boost_utc_add<long long int>::op_boost_utc_add()’ first required here 
     p_l_t r = op_boost_utc_add<long long>()(a, b, c);
                                           ^
[d257414 boost]$clang++ -g -o add add.cpp -I${BOOST_ROOT_DIR} -I${BOOST_SIMD_DIR}/include -msse4.1 -std=c++11 -stdlib=libc++ -lc++abi
[d257414 boost]
```

**Comment by saibing** [comment] 2015-10-27 10:31
Move constant definition to the function body, gcc compile passed.

``` cpp
p_t operator()(p_t const &a0, p_t const &a1, p_t const &delta)
{
    const p_t seconds_in_one_day = splat<p_t>(static_cast<T>(SECONDS_IN_ONE_DAY));
    return evaluate(a0 + (seconds_in_one_day * a1) + delta);
}
```

**Comment by jfalcou** [comment] 2016-04-30 17:44
This seems to be working under the current standalone boost.SIMD version. 
I added your test case to our regression test suite. If this pass Travis, I'll close this issue as being fixed by the new version.

**Comment by jfalcou** [comment] 2016-05-19 07:34
https://github.com/NumScale/boost.simd/blob/develop/test/regression/issue_21.cpp

is now the proper way to write your code using new Boost.SIMD.
Note that long long is not a valid type to use pack with. Use the stdandard sized type instead (std::int64_t).

**Closed as completed by jfalcou** 2016-05-19 07:34 UTC
Labels: bug
