### ISSUE TITLE
Prevent internal includes to accidentaly forgot to include all version of a function

### ISSUE THREAD

**Issue by otristan** [agenium-scale/boost.simd#268] opened 2016-09-12 14:01 UTC
Hi,

The following code

```
pack<int16_t, 8> a;
auto b = shuffle<0, 2, 4, 6, 8, 1, 3, 5, 7>(a);
```

use to produce a vpshufb in 216040519d2a5d93ffb912e7c7d7ad23b8694566

but it doesn't work anymore.

_Weird thing is that I see that this is an AVX2 opcode although my CPU do not handle it (i7-3770K). (it used to work fine though)_ <---- Nevermind PSHUFB __m128 version does exists in AVX, only the __m256 version does not.

More generally I see a big drop in performance regarding this particular code between the trunk and the revision I have mentioned.

Any ideas ?

Thanks !

**Comment by otristan** [comment] 2016-09-12 15:04
Something related to the loss of `simd\arch\x86\ssse3\simd\function\hmsb.hpp` ?

**Comment by otristan** [comment] 2016-09-12 16:34
Looks like it's not limited to this instruction.
I get very bad performance on VS2015 using the latest trunk.

**Comment by otristan** [comment] 2016-09-12 16:45
Issue is already there in 6784f032f31ff704348c3d1d5d509fdf3255fabd

**Comment by jfalcou** [comment] 2016-09-12 18:24
Can you tell me what performance you get from   06c1b8d ?

**Comment by jfalcou** [comment] 2016-09-12 18:51
The issue comes from  4f0a6c3 as performance from  678517f are correct.
Investigating.

**Comment by jfalcou** [comment] 2016-09-12 19:18
OK, reverting 3abfb46 fix the regression. Now to see why and fix it properly.

**Comment by jfalcou** [comment] 2016-09-12 19:20
Care to test reverting it on your side and check ?

**Comment by jfalcou** [comment] 2016-09-12 19:55
OK, is your code similar to the one you sent me ?? Cause if this is the case, the issue is that you lack includes for shuffle and tofloat, so only the scalar version is seen and included, leading to the function being emulated. I got correct performances on develop by adding said include.

The relationship with the fix_268 branch is that something in the internal include changed when we move to a split between scalar & simd from generic version some commits ago.

We need to protect us from such errors though :/

**Comment by otristan** [comment] 2016-09-13 07:36
The code is similar to the one I have sent you.
Adding includes fixes my issue.

Would be best indeed if I had some compile error regarding the missing includes :)

Thanks !

**Comment by jfalcou** [comment] 2016-09-13 08:22
Let me reuse this issue then.
The fact is that we can't really know the file is missing, some SIMD unction just don't exist and require emulation. What we need to do is make a global pass to ensure that accidental internal includes don't pull half of what's needed.

**Comment by jfalcou** [comment] 2016-09-14 14:07
The now merged branch fix all includes so all functions are properly included to prevent performances issue because an include was missed.

**Closed as completed** 2016-09-14 14:06 UTC
Labels: in-progress

**Comment by otristan** [comment] 2016-09-14 14:42
I confirm.

Thanks !
